### ISSUE TITLE
Remove the jQuery dependency

### ISSUE THREAD

**Issue by fredck** [quailjs/quail#100]
Steps to complete this issue

- [x] Replace the current jQuery default build with a custom build that does not include transition
- [x] animations and other behaviors that we don't use.
- [x] Refactor the :quailCss pseudo-selector, among other non-standard jQuery selectors like :has, :input.
Replace jQuery whole-cloth with smaller, focused

## Description

Being QUAIL a generic js library, wouldn’t it be better to remove the jQuery dependency out of it?

jQuery is a 93KB file and in fact QUAIL is using just a small part of it. Actually, the most use for it is the CSS selector stuff and a few tools, like each().

There are several CSS selectors libs out. Sizzle is the most obvious option, but there are even more compact solutions. In fact, QUAIL is not using ultra-complex selectors and eventually a simpler lib would do the job as well. Still Sizzle would be better with 1/5 of jQuery's size.

As for the tools, that’s just js programming style. Still, if some tools are needed, it is enough to decouple the small bits of source code from jQuery or any other js lib out there, having only the stuff that is really needed.

As for jQuery, it would still be possible to the make QUAIL a plugin for it. This would add just a few bits of code to QUAIL.

Anyway, I’m actually just opening a discussion here, to check if it makes any sense investigating it further. Thanks!

**Comment by mlewand** [comment]
@srounce In fact it wasn't removed, I'll reopen this issue to continue discussion.

@fredck As for selector engine, don't really even need to use Sizzle here. Ideally we would like to use [Element.querySelectorAll](https://developer.mozilla.org/en/docs/Web/API/Element/querySelectorAll).

To sum current arguments and add few more:

* reviewing jQuery code, gives us a better chances to spot some problems (like sync ajax calls, that was the most severe for us #332, cksource/quail#16)
* initially I thought that selector performance won't change so much, but when I took `:quailCss` pseudo-class selector, and transformed it to use native DOM operations - execution time was reduced **4 times** (actually it was 4.8x so it was even closer to 5)
* code size will be reduced a lot

**Comment by jessebeach** [comment]
From our call on July 23rd, 2015:

We'll take a phased approach to removing jQuery.

1. Replace the current jQuery default build with a custom build that does not include transition, animations and other behaviors that we don't use.
1. Refactor the ```:quailCss``` pseudo-selector, among other non-standard jQuery selectors like ```:has```, ```:input```.
1. Replace jQuery whole-cloth with smaller, focused

**Comment by jessebeach** [comment]
Ok, I think we can finally achieve this in the master branch.

**Comment by jessebeach** [comment]
jQuery is out. 

I've put a build process in place that runs the code through Babel for transpiling. 

https://github.com/quailjs/quail/pull/390/
