### ISSUE TITLE
Test for WCAG technique SCR31: Using script to change the background color or border of the element with focus

### ISSUE THREAD

**Issue by hannolans** [quailjs/quail#115]
http://www.w3.org/WAI/GL/WCAG20/WD-WCAG20-TECHS/SCR31
This purpose of this technique is to allow the author to use JavaScript to apply CSS, in order to make the focus indicator more visible than it would ordinarily be. When an element receives focus, the background color or border is changed to make it visually distinct. When the element loses focus, it returns to its normal styling. This technique can be used on any HTML user agent that supports Script and CSS, regardless of whether it supports the :focus pseudoclass.

Procedure

1. Tab to each element in the page
2. Check that the focus indicator is visible

Expected Results

* Step #2 is true

**Comment by jessebeach** [comment]
Fixed with https://github.com/quailjs/quail/pull/325
