### ISSUE TITLE
PhantomJS limitations regarding audio/media tests

### ISSUE THREAD

**Issue by theodoreb** [quailjs/quail#254]
Current stable version of PhantomJS has no audio/video support (ariya/phantomjs#11664) it is planned for PhantomJS 2.0 for which there is no timeline yet. 

It means I doubt we have what we need to implement any of the following tests: 

* #247
* #246 
* #208

**Comment by jessebeach** [comment]
The master branch is switched to Selenium, this is no longer an issue.
