### ISSUE TITLE
jQuery plugin is not behaving as expected

### ISSUE THREAD

**Issue by theodoreb** [quailjs/quail#255]
there is a quail.html property that is supposed to have the current DOM element being processed by quail. It's not true. 

```html
<div data-quail-test id="test1"></div>
<div data-quail-test id="test2"></div>
```

and 
```javascript
$('[data-quail-test]').quail({});
```

`quail.html` will contain the jQuery object with the two results, I'd expect quail.html to be the individual div. Basically need to be using `$(this).each()` in the quail function:

```javascript
$(this).each(function (index, element) {
  quail.options = options;
  quail.html = $(element);

  quail.run(options);
});
```

It's only a problem for people looking at extending quail or for quail's own tests. Not sure how much breaks if we do that (apparently not much, tests are still passing).

**Comment by jessebeach** [comment]
Ya, this nonsense is all going away in the #289 branch. We'll be testing Quail's data output using Mocha/Chai assertions. No more specialized testing HTML.

**Comment by jessebeach** [comment]
Oh, and I've built in single test runs from the get-go :)

**Comment by jessebeach** [comment]
The jQuery plugin is going away. We'll just expose a ```quail``` object in the DOM.
