### ISSUE TITLE
Quailjs file  from git source doesn't work on the simple sample

### ISSUE THREAD

**Issue by sirius2013** [quailjs/quail#264]
I got issue when use the quail.jquery.js file from this github source.
First of all the file size is bigger than same file from quailjs.org.
As you can see image, 218KB vs 61KB.
and I tested with 218KB(from Github), it doesn't work on my side.
I debugged something, but there is code part about testFail callback.

https://cloud.githubusercontent.com/assets/5020713/3791901/ecbfc29a-1b59-11e4-9451-2ac077d3ea42.png

simple example works fine with this js.
http://quailjs.org/dist/quail.jquery.js

I want to know why it doesn't work with js file from github source.

Look forward to your hearing.
Thanks so much

**Comment by jessebeach** [comment]
Hopefully these issues will be addressed in the refactor in master. I'm not sure what the specific problem is.
