### ISSUE TITLE
Review on a11y tests directory structure

### ISSUE THREAD

**Issue by fredck** [quailjs/quail#269]
Warning: Big change!

Currently a single a11y test is potentially represented by a series of files spread at different places of the repo. For example, we could have the following for a “custom” test:

* test/accessibility-tests/testid.html
* src/resources/tests/tests.yml (all tests together)
* src/js/custom/testid.js
* Am I missing something?

I was wondering if it would be possible to have a better maintainable approach, with a structure like this:

```
/a11ytests/
	/testid/
		/test.yml (extracted from tests.yml)
		/custom.js
		/lang/
			en.pot
			nl.po
			pl.po (…)
		/tests/
			testid.html
			testid-2.html (…)
```

In other words, having all the information, code and tests for each a11y test placed in a dedicated and easy to find folder.

Additionally, I’m proposing the creation of separate folder for translations, to avoid having to touch the description file (test.yml) with i18n stuff. For the sake of making it more interesting, I’ve used pot and po extensions, but ofc they could be yml or json files.

We could even argue about the sense of keeping test.yml instead of making it test.json.

The proposed structure has also an important role, as we want to enable others to write custom tests to be included in a quail build. It would be enough to point to a local folder with custom tests then.

**Comment by jessebeach** [comment]
I've redone the structure here https://github.com/quailjs/quail/pull/386 and here https://github.com/quailjs/quail/pull/387.
