### ISSUE TITLE
Add JSCS for plug-in coding standards

### ISSUE THREAD

**Issue by nschonni** [quailjs/quail#278]
https://github.com/jscs-dev/node-jscs is replacing the style relate lints from JSHint, so it might be good to start looking at it now. @jessebeach's code review in #277 that we can automate alot of that. I'll see if I can get a PR together, but I wanted to create an issue so someone else can tackle it if I forget.

Rules: https://github.com/jscs-dev/node-jscs#rules althought I'd recommend starting with the jQuery preset, and then enabling/disableing rules on top of that

Grunt plug-in: https://github.com/jscs-dev/grunt-jscs/

**Comment by jessebeach** [comment]
This is now running in the master branch.
