### ISSUE TITLE
Have the testrunner check the element

### ISSUE THREAD

**Issue by WilcoFiers** [quailjs/quail#303]
Cases often returns a DOM element. The testrunner should check if this element was the actual element which should have that specific result. I ren into this with videosEmbeddedOrLinkedNeedCaptions which returned a jQuery selector instead of a DOM element, which caused a problem when creating a CSS path for the element.

**Comment by jessebeach** [comment]
The individual assessment needs to check this. The testrunner doesn't have the context necessary to make this distinction.
