### ISSUE TITLE
data-cacheid aren't cleaned up before code snippets are taken

### ISSUE THREAD

**Issue by WilcoFiers** [quailjs/quail#350]
I've been finding a lot of data-cacheid attributes in the code snippets returned by Quail. I *think* this is caused by the color tests. This may be confusing to users.

**Comment by baldwicc** [comment]
Using [`elem.dataset`](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes#JavaScript_Access) or [`jQuerydata()`](https://api.jquery.com/jquery.data/) should keep these out of the DOM.

**Comment by baldwicc** [comment]
Tried using dataset but it threw `TypeError: 'undefined' is not an object (evaluating 'element.dataset.cacheId')` during testing.  

Pretty sure I'm missing something obvious here, but the jQuery .data() method seems to work and gets rid of these data-cacheid attributes in reports.

**Comment by jessebeach** [comment]
Fixed by PR #360 .
