### ISSUE TITLE
Can't get quail jQuery plugin to start?

### ISSUE THREAD

**Issue by kahunacohen** [quailjs/quail#355]
I'm playing with Quail on a very simple web page:
http://www.kahunacohen.com/quail/t2.html

But a number of tests are failing and I don't understand why. For example in the console you can see that "linkDoesNotChangeContextOnFocus" fails. It reports the problem is with h1 element. Link elements must not contain an "onfocus" attribute. I am totally confused by this. The h1 element has no link element inside it and there are no onfocus attrs in either the source or in the generated DOM... I tried:

```
getEventListeners($("body").get(0))
```
in firebug and see no event handlers...

**Comment by jessebeach** [comment]
kahunacohen, what branch or checkout are you using?

**Comment by kahunacohen** [comment]
Hi. Thanks for answering. QUAIL looks great if I can get it running our organization would definitely be a significant contributor. If you look at the net tab, I'm just loading the same code as the example is from the quail site:
http://quailjs.org/dist/quail.jquery.min.js
I am printing the failing tests to console using the testFailed callback.

**Comment by jessebeach** [comment]
Aha! That build is very old. And unfortunately I do not have access to the code on that domain. @kevee controls the domain and he's been unresponsive for the past year. We all hope he's OK.

Use the 2.2.17 branch: https://github.com/quailjs/quail/tree/2.2.17

You'll need to build it. Follow the steps in the README

I usually run Quail from the command line rather than embedding it as a jQuery plugin.

**Comment by kahunacohen** [comment]
OK. I'll try it out. We would want to do both. As I said we use our own tool for accessiblity checks. We are a govt org (NCBI) and if this suits our needs we would be happy to take on some work ourselves.

**Comment by kahunacohen** [comment]
OK, so I built quail as per the instructions, renamed the dist directory "resources", stuck it next to my web page, and run it and now no callbacks are fired, even though clearly there is an img with no alt. I am following instructions here: http://quail.readthedocs.org/en/latest/.

Here is the page. Please tell me why no callbacks are being fired. Probably something easy I am missing...
http://www.kahunacohen.com/quail/t3.html
No errors and all scripts are loaded. I am calling quail at the end of the document, so that img node should be loaded. I even tried calling quail on ready, no dice...

**Comment by jessebeach** [comment]
Thank you for the thorough test case! I'll have a look.

**Comment by kahunacohen** [comment]
Any progress? If it's not obvious I could start to trace through the code.

**Comment by jessebeach** [comment]
No, not yet. It's on my todo list, but lower in priority than #333 .

Try running the following on the page and see if you can get a debugger to catch in any of the event handlers.

```javascript
jQuery('html').quail({
  jsonPath: 'resources',
  // Called when an individual Case in a test is resolved.
  caseResolve: function (eventName, test, _case) {},
  // Called when all the Cases in a Test are resolved.
  testComplete: function (eventName, test) {},
  // Called when all the Tests in a TestCollection are completed.
  testCollectionComplete: function (eventName, testCollection) {},
  // Called when all TestCollections are completed.
  quailComplete: function (eventName) {},
  // Called when all Success Criteria have evaluated.
  successCriteriaEvaluated : function (eventName, successCriteria) {}
});
```

I promise this is all much cleaner in the next version :)

**Comment by jessebeach** [comment]
This is working fine in the master branch.
