### ISSUE TITLE
Update NPM Package

### ISSUE THREAD

**Issue by JLLeitschuh** [quailjs/quail#361]
The NPM package is still on 2.1.1
https://www.npmjs.com/package/quail

**Comment by jessebeach** [comment]
Yes, it'll be updated when we move to the 3.0 release. It's getting close. I predict before 2016.

**Comment by JLLeitschuh** [comment]
Any update on this?

**Comment by jessebeach** [comment]
Yes, I've pulled the project into three repos and put them under the @quailjs namespace on npm: https://www.npmjs.com/org/quailjs
