### ISSUE TITLE
Extract KING Tests

### ISSUE THREAD

**Issue by mlewand** [quailjs/quail#364]
Some KING tests are included in the core of QUAIL and should be extracted and handled in independent ways.

We should discuss what will be the most convenient way for 3rd parties to extend Quail with their own tests. Then we should also document as a recommended way, to make life of others a little easier.

- [ ] decide what is the best way for 3rd parties to add tests,
- [ ] document it as a recommended way to extend Quail

**Comment by mlewand** [comment]
I can also recall @WilcoFiers having a nice idea of separating a core Quail part lets call it "assessments runner" from the assessments, Wilco maybe you could elaborate more on this idea? Perhaps here or by creaing a new issue.

**Comment by jessebeach** [comment]
Related to #368

**Comment by jessebeach** [comment]
The assessment files still exist in the quail repo, but they will no longer be built into quail. We'll move them out of this repo and into a KING repo later.
