### ISSUE TITLE
Enhance builder

### ISSUE THREAD

**Issue by mlewand** [quailjs/quail#367]
This actually strongly depends on the outcome of tickets:

* #270 #269
	Since these tasks will modify directory structure, so there's reason to start builder without these issues ready.
* #364
	Because it might make sense to accept extra path as an cli argument for `grunt build` task e.g. `grunt build --tests="/var/workspace/quail/customTests"`. Then it might simply include tests given in a specified directory.

**Comment by jessebeach** [comment]
Covered by: #365, #368
